### ISSUE TITLE
Configuration of TYPO3_CONF_VARS is wrong in OpenidEid

### ISSUE THREAD

**Issue by tottt** [FriendsOfTYPO3/openid#10]
I found the the config array should be
`$GLOBALS['TYPO3_CONF_VARS']['SVCONF']['auth']['setup']['FE_fetchUserIfNoSession'] = true;`

I guess you missed the "[setup]" part. At least it did not work in my install untill i added it.
(TYPO3 7.6; PHP 5.6)

**Comment by liayn** [comment]
That's right and I guess you're the first one discovering this after a very long time... line is there since 28.10.2008
