### ISSUE TITLE
PHP Bug: Call to a member function rowCount() on integer 

### ISSUE THREAD

**Issue by oaltmann** [FriendsOfTYPO3/openid#15]
Hi!

I have a i issue, If I want to login I get an exception: 

> Call to a member function rowCount() on integer 

Error thrown in file
/Users/oaltmann/PHPStorm_Projektdaten/T3Res_8/public_html/typo3conf/ext/openid/Classes/OpenidStore.php in line 99.

I can fix this Problem with this code:

    /**
     * Removes all expired associations.
     *
     * @return int A number of removed associations
     */
    public function cleanupAssociations()
    {
        $queryBuilder = GeneralUtility::makeInstance(ConnectionPool::class)->getQueryBuilderForTable(self::ASSOCIATION_TABLE_NAME);
        $queryBuilder->getRestrictions()->removeAll();
        //return $queryBuilder->delete(self::ASSOCIATION_TABLE_NAME)->where('expires <= ' . time())->execute()->rowCount();
        return $queryBuilder->delete(self::ASSOCIATION_TABLE_NAME)->where('expires <= ' . time())->execute();
    }

But after the fix a can't login. 
The openid server is called but After the request I am back in the login area with this parameters:

typo3/index.php?login_status=login&tx_openid_location=http%3A%2F%2Ft3res87.local%3A8888%2Ftypo3%2Findex.php%3FloginProvider%3D1433416748&tx_openid_location_signature=9891847d83d9b31d82c1ba5144f52336bc0f01a5&tx_openid_mode=finish&tx_openid_claimed=https%3A%2F%2Foaltmann.id.tankom.de%2F&tx_openid_signature=069e609d05e23adfd31f13a73bab2848a1d09f8b&janrain_nonce=2017-04-05T07%3A20%3A00ZlV8tku&openid1_claimed_id=https%3A%2F%2Foaltmann.id.tankom.de%2F&openid.assoc_handle=%7BHMAC-SHA1%7D%7B58e49a9d%7D%7B7OG%2BLw%3D%3D%7D&openid.identity=https%3A%2F%2Foaltmann.id.tankom.de%2F&openid.mode=id_res&openid.response_nonce=2017-04-05T07%3A20%3A02ZtgXgDb&openid.return_to=http%3A%2F%2Ft3res87.local%3A8888%2Ftypo3%2Findex.php%3Flogin_status%3Dlogin%26tx_openid_location%3Dhttp%253A%252F%252Ft3res87.local%253A8888%252Ftypo3%252Findex.php%253FloginProvider%253D1433416748%26tx_openid_location_signature%3D9891847d83d9b31d82c1ba5144f52336bc0f01a5%26tx_openid_mode%3Dfinish%26tx_openid_claimed%3Dhttps%253A%252F%252Foaltmann.id.tankom.de%252F%26tx_openid_signature%3D069e609d05e23adfd31f13a73bab2848a1d09f8b%26janrain_nonce%3D2017-04-05T07%253A20%253A00ZlV8tku%26openid1_claimed_id%3Dhttps%253A%252F%252Foaltmann.id.tankom.de%252F&openid.sig=gY%2FOdG%2Fsy1AYZ9dtMblMBrPvi7A%3D&openid.signed=assoc_handle%2Cidentity%2Cmode%2Cresponse_nonce%2Creturn_to%2Csigned

Does anyone have a solution for this?

Thanks.

**Comment by liayn** [comment]
I can confirm the issue. But I first need to get a new openid identity working, since my old provider stopped the service. Once I know the new one works correctly, I can try fixing this.

The solution above is correct, still it returns some weird error messages. So I need to investigate that.
Maybe there is one more update available for the underlying library of openid.

**Comment by vandres** [comment]
We created a pull request #16 which probably fixes the issue. Feedback is welcome :)

**Comment by liayn** [comment]
> Maybe there is one more update available for the underlying library of openid.

Answering to myself: no, there isn't any update.
