### ISSUE TITLE
Openid login not working on current master

### ISSUE THREAD

**Issue by georgringer** [FriendsOfTYPO3/openid#2]
After login via openid the redirect is broken.

Redirect target:

http://typo3-core.dev/typo3/index.php?login_status=login&tx_openid_location=http%3A%2F%2Ftypo3-core.dev%2Ftypo3%2Findex.php%3FloginProvider%3D1433416748&tx_openid_location_signature=e1549ce9cfa8e6be55bee307a952851ee2409557&tx_openid_mode=finish&tx_openid_claimed=https%3A%2F%2Fme.yahoo.com%2Fa%2FMNzxCfkDu86cuiZg_VM_7K6BzRy1RdmvwFTN&tx_openid_signature=f6eb5cd3f85caf04c8434842e48783ec8e32bf1f&janrain_nonce=2015-08-08T08%3A56%3A35ZDHnikK&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.return_to=http%3A%2F%2Ftypo3-core.dev%2Ftypo3%2Findex.php%3Flogin_status%3Dlogin%26tx_openid_location%3Dhttp%253A%252F%252Ftypo3-core.dev%252Ftypo3%252Findex.php%253FloginProvider%253D1433416748%26tx_openid_location_signature%3De1549ce9cfa8e6be55bee307a952851ee2409557%26tx_openid_mode%3Dfinish%26tx_openid_claimed%3Dhttps%253A%252F%252Fme.yahoo.com%252Fa%252FMNzxCfkDu86cuiZg_VM_7K6BzRy1RdmvwFTN%26tx_openid_signature%3Df6eb5cd3f85caf04c8434842e48783ec8e32bf1f%26janrain_nonce%3D2015-08-08T08%253A56%253A35ZDHnikK&openid.claimed_id=https%3A%2F%2Fme.yahoo.com%2Fa%2FMNzxCfkDu86cuiZg_VM_7K6BzRy1RdmvwFTN%23715df&openid.identity=https%3A%2F%2Fme.yahoo.com%2Fa%2FMNzxCfkDu86cuiZg_VM_7K6BzRy1RdmvwFTN&openid.assoc_handle=uF_FEAFNu21dCt1wzt8Fq7oc3CQhf3zQkcRt9EPxtEXejHUWHEtUCrTMm_uja2Gdgy9UFuRZ8SuNAfW_O_fiAbe8cZJB2eOR9spKmMRi7ZAuUrGmTBe1fgjAiiVKSwMz.rxEJA--&openid.realm=http%3A%2F%2Ftypo3-core.dev%2F&openid.response_nonce=2015-08-08T08%3A56%3A30ZNx82ncvsLatHESKqZHq8YpTHe_7MkYz4aQ--&openid.signed=assoc_handle%2Cclaimed_id%2Cidentity%2Cmode%2Cns%2Cop_endpoint%2Cresponse_nonce%2Creturn_to%2Csigned%2Cpape.auth_level.nist&openid.op_endpoint=https%3A%2F%2Fopen.login.yahooapis.com%2Fopenid%2Fop%2Fauth&openid.pape.auth_level.nist=0&openid.sig=2MIUoHeWonfSxZ8FVeYpftVgtZs%3D
You stuck at the login screen without CSS etc. see screenshot attached.

https://forge.typo3.org/issues/68857

**Comment by liayn** [comment]
Is this still an issue on the 7 LTS release?
I'm not aware of any issue in this regard.
