### ISSUE TITLE
Exception when user name and/or password are incorrect in Frontend

### ISSUE THREAD

**Issue by dmitryd** [FriendsOfTYPO3/openid#24]
Exception happens when trying to login with user name and password but one or both are wrong:

```
Call to a member function setTSlogMessage() on null 

Error thrown in file
/home/kruegertest/web/typo3conf/ext/openid/Classes/OpenidService.php in line 592.
```

More on the screenshot:
<img width="489" alt="exception" src="https://user-images.githubusercontent.com/306133/46795694-801a7f80-cd53-11e8-9e7d-c97e38250019.png">

**Comment by dmitryd** [comment]
@liayn Thank you!

**Comment by liayn** [comment]
Release is out as well
