### ISSUE TITLE
Table tx_openid_nonce_store cannot be created in TYPO3 v9.5.1

### ISSUE THREAD

**Issue by frius94** [FriendsOfTYPO3/openid#26]
After adding the extension I tried to create the new table tx_openid_nonce_store from the backend.
Maintenance -> Analyze Database -> Apply selected changes
The following query was selected:

`CREATE TABLE `tx_openid_nonce_store` (`uid` INT UNSIGNED AUTO_INCREMENT NOT NULL, `pid` INT UNSIGNED DEFAULT 0 NOT NULL, `crdate` INT UNSIGNED DEFAULT 0 NOT NULL, `tstamp` INT UNSIGNED DEFAULT 0 NOT NULL, `server_url` VARCHAR(2047) DEFAULT '' NOT NULL, `salt` VARCHAR(40) DEFAULT '' NOT NULL, UNIQUE INDEX `nonce` (server_url(255), tstamp, salt), INDEX `crdate` (crdate), PRIMARY KEY(uid)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB`

I got the following response:
`ERROR 1709 (HY000): Index column size too large. The maximum column size is 767 bytes.`

Why can't this table be created? Is it possible that, the size of the columns for the index 'nonce' is too big?
I am using TYPO3 v9.5.1.

innodb_large_prefix --> ON
innodb_file_format --> Barracuda

**Comment by liayn** [comment]
I think this is indeed related to the size of the server_url. 255 times 4 bytes is larger than 767 bytes.
Which version of mysql is in use?

**Comment by frius94** [comment]
10.1.37-MariaDB-0+deb9u1

**Comment by liayn** [comment]
see also https://stackoverflow.com/a/48827653/7206911

**Comment by liayn** [comment]
Question is whether we really need multibyte support for the server_url. we could maybe change this for that field or table

**Comment by frius94** [comment]
I changed the query statement to:

`CREATE TABLE `tx_openid_nonce_store` (`uid` INT UNSIGNED AUTO_INCREMENT NOT NULL, `pid` INT UNSIGNED DEFAULT 0 NOT NULL, `crdate` INT UNSIGNED DEFAULT 0 NOT NULL, `tstamp` INT UNSIGNED DEFAULT 0 NOT NULL, `server_url` VARCHAR(2047) DEFAULT '' NOT NULL, `salt` VARCHAR(40) DEFAULT '' NOT NULL, UNIQUE INDEX `nonce` (server_url(255), tstamp, salt), INDEX `crdate` (crdate), PRIMARY KEY(uid)) DEFAULT CHARSET = utf8 COLLATE utf8_general_ci ENGINE = InnoDB;`

and it worked. Thanks!

**Comment by liayn** [comment]
Well, we need to deploy this as well with the extension I guess
