### ISSUE TITLE
Add support for TYPO3 v10

### ISSUE THREAD

**Issue by dmitryd** [FriendsOfTYPO3/openid#27]
This ticket is created to reference it in the pull request. Subject says it all.

**Comment by dmitryd** [comment]
Pull request: https://github.com/FriendsOfTYPO3/openid/pull/28

**Comment by liayn** [comment]
@dmitryd Are you satisfied with the current state of the extension for v10?

**Comment by dmitryd** [comment]
@liayn Do you know if it works with the new TYPO3 cookie policy?

**Comment by liayn** [comment]
I'm sorry, I don't know. See also https://github.com/FriendsOfTYPO3/openid/issues/29#issuecomment-610234042 please.
If you are keen on maintaining the extension again, feel free and let me know.

**Comment by dmitryd** [comment]
@liayn I can take over. Hopefully I will have time this week to check with v10 but I think I will need to add a modification for `TYPO3_CONF_VARS` in the extension to let the ext work out of the box.

**Comment by haassie** [comment]
Hi @dmitryd and @liayn. We use this extension for all our installations and are working on v10 upgrades as well. Will ask my colleagues to test this patch.

**Comment by liayn** [comment]
@haassie No need to test this patch. All changes should already be in the master branch. Out of curiosity: Which provider do you use?

@dmitryd Okay. I'll then transfer the ext key in TER to you.

**Comment by haassie** [comment]
@liayn well, our main issue https://github.com/FriendsOfTYPO3/openid/blob/master/ext_tables.sql#L47 is still in Resulting in errors in our installations. See https://github.com/FriendsOfTYPO3/openid/issues/30.

We are using https://www.atlassian.com/nl/software/crowd since a long time for our authentication and use the Crowd OpenID server with that.

**Comment by dmitryd** [comment]
@haassie You can try 10.0.1

**Comment by haassie** [comment]
Thanks @dmitryd. Everything seems to work fine!
