### ISSUE TITLE
lib/php-openid/Auth/OpenID/AX.php needs to be manually required when using the getUser() hook

### ISSUE THREAD

**Issue by josefglatz** [FriendsOfTYPO3/openid#33]
Hi,

I'm using the actual stable version 10.0.1 of ext:openid within TYPO3 9.5.19 in composer mode. The login process works as expected. In my used hook `$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['openid']['getUserRecord']`  I'm using `\FoT3\Openid\OpenidService::$openIDResponse` which is the object `\Auth_OpenID_ConsumerResponse`. Is it intentionally thought that you have to require the class in you hook implementation manually like so:

```php
set_include_path(ExtensionManagementUtility::extPath('openid') . 'lib/php-openid' . PATH_SEPARATOR . get_include_path());
require_once 'Auth/OpenID/AX.php';
```

I would have assumed that `ext:openid` requires openid/php-openid library if I require the extension with composer.

cheers,  
Josef

**Comment by dmitryd** [comment]
> I would have assumed that ext:openid requires openid/php-openid library if I require the extension with composer.

It does not because library needs changes for running with TYPO3. Therefore we bundle it locally. The library does not use namespaces, therefore we cannot reference it in `composer.json`.
