### ISSUE TITLE
Backend User Settings not working: getTSConfigProp() is deprecated

### ISSUE THREAD

**Issue by oaltmann** [FriendsOfTYPO3/openid#34]
Hi!

I use TYPO3 10.4.5 with openID 10.0.0. When I open the user settings in the head of the backend I get the following error message:
![Bildschirmfoto 2020-07-08 um 10 41 14](https://user-images.githubusercontent.com/26857059/86899703-a62ca980-c10a-11ea-918b-7cb3f5747faa.png)

The problem can be solved with the following code:
File: /openid/Classes/OpenidModuleSetup.php (Line 35)

`
old: $setupConfig = $this->getBackendUser()->getTSConfigProp('setup.fields');
new: $setupConfig = $this->getBackendUser()->getTSConfig('setup.fields');`

Can you fix the issue?

**Comment by djcprinse** [comment]
This should be fixed in the recently released version v10.1.0. I faced the same issue and my patch has been merged and @bmack released a new version containing that patch.

**Comment by dmitryd** [comment]
Fixed already :)
