### ISSUE TITLE
Backend User Settings not working: getModuleUrl() is deprecated

### ISSUE THREAD

**Issue by oaltmann** [FriendsOfTYPO3/openid#35]
Hi!

When i open the user settings in head of the TYPO3 10.4.5 backend with openID 10.0.0. I find this issue:
![Bildschirmfoto 2020-07-08 um 10 41 49](https://user-images.githubusercontent.com/26857059/86899808-c6f4ff00-c10a-11ea-99b1-7ff2544bf020.png)

File: openid/Classes/OpenidModuleSetup.php (LINE 52)
`old: $popUpUrl = GeneralUtility::quoteJSvalue(BackendUtility::getModuleUrl('wizard_openid', $parameters));`
`new: $uriBuilder = GeneralUtility::makeInstance(UriBuilder::class);
$popUpUrl = GeneralUtility::quoteJSvalue($uriBuilder->buildUriFromRoute('wizard_openid', $parameters));`

Don't forget the namespace: use TYPO3\CMS\Backend\Routing\UriBuilder;

Can you fix this issue?

**Comment by djcprinse** [comment]
This should be fixed in the recently released version v10.1.0. I faced the same issue and my patch has been merged and @bmack released a new version containing that patch.

**Comment by dmitryd** [comment]
Fxied already :)
