### ISSUE TITLE
OpenID in BE-Login doesn't work with IE11 since the password will always be set

### ISSUE THREAD

**Issue by erredeco** [FriendsOfTYPO3/openid#4]
Since TYPO3 assumes a "normal" Login if a password is provided, it doesn't work in IE11. IE seems to deliver the placeholder attribute of the input field. So the password field always contains a password, so the OpenID will never be triggered and the login will fail.

To reproduce
- IE bug: Try to login with an IE11 in TYPO3 backend with an OpenID without a password -> login fails
- Behaviour in all browser: use an OpenID in user field, add a password in the password field -> login fails
  Tested in TYPO3 6.2.9

https://forge.typo3.org/issues/64552

**Comment by liayn** [comment]
I'll check if this is still the case with CMS 7.
If a fix for 6.2 is necessary, I will handle this in the ticket linked above.

**Comment by liayn** [comment]
Version 7 does not seem to have this issue, it works fine on IE11. Closing this issue.
