### ISSUE TITLE
correct composer.json

### ISSUE THREAD

**Issue by josefglatz** [FriendsOfTYPO3/openid#9]
It must be possible to require this github repo within the root composer.json of a TYPO3 project.

**Comment by liayn** [comment]
What has to be done in the file?

**Comment by helhum** [comment]
composer.json looks good in general, but maybe change the composer name to fot/openid ?

**Comment by liayn** [comment]
It should be similar to https://github.com/FriendsOfTYPO3/tt_address/blob/master/composer.json I guess, which has `friendsoftypo3/tt-address`

**Comment by helhum** [comment]
yupp, that'd be fine
